# Generated by Django 5.2.6 on 2025-10-26 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0004_alter_usuarios_email_delete_credenciais"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credenciais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20)),
                ("suap_token", models.CharField(max_length=255)),
                ("bearer", models.CharField(max_length=255)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuarios",
                    ),
                ),
            ],
        ),
    ]
