# Generated by Django 5.2.6 on 2025-10-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credenciais",
            name="numero",
        ),
    ]
