# Generated by Django 5.2 on 2025-11-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmensagens",
            name="ativo",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.CreateModel(
            name="SupportReplyMensagens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("dev_responsavel", models.CharField(max_length=255)),
                (
                    "support",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Dashboard.supportmensagens",
                    ),
                ),
            ],
        ),
    ]
