# Generated by Django 5.2.6 on 2025-11-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuarios_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='data_ultimo_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='matricula',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuário'),
        ),
    ]
