#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

echo "Carregando fixtures..."
python manage.py loaddata app/fixtures/*.json || echo "Nenhum fixture encontrado ou já carregado."

python manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn core.wsgi --bind 0.0.0.0:5000 --chdir=/app